version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: easyshare/client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
    backend:
        container_name: server
        build:
            context: ./
            dockerfile: Dockerfile
        image: easyshare/server
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/app